### ISSUE TITLE
Proposal: Embed the metadata in mdx file frontmatter

### ISSUE THREAD

**Issue by t0t07** [jaredpalmer/nextra-blank-custom-theme#2]
This way, instead of having the posts.json that lists everything in detail, we embed these metadata in frontmatter of each mdx files.

For example,

```
---
title: Another One
slug: /blog/another-one
date: June 16, 2020
---
```

@jaredpalmer What do you think?

**Comment by jaredpalmer** [comment]
As I mentioned in the readme, you can do this by making a blank `index.mdx` and then looping through and sorting etc. in `layout.js` if `route === '/'` or something. Goal of this was to show folks what's possible and how simple nextra is to work with
